### ISSUE TITLE
Please add postalcode to bundles

### ISSUE THREAD

**Issue by vesameskanen** [whosonfirst/py-mapzen-whosonfirst-bundles#4]
wof-postalcode-latest.csv seems to be empty at the moment. It would be nice to get that data into the bundles as well. We would use it to add missing postalcodes to our Pelias geocoding data.

**Comment by thisisaaronland** [comment]
Hopefully, this will be sorted out by the middle of next week. I will spare you to boring details until I have to bore you with the details to explain why it's more complicated than I'd hoped, but hopefully it won't be.

This is all wrapped up in some of the discontinuities around how placetypes and individual repos are organized and how the code has evolved around those facts. But you are not the only person asking for stuff like this so it's time...

More soon!

**Comment by thisisaaronland** [comment]
Notes to self:

This assumes you're already in `whosonfirst-data-postalcode-fi`

```
wof-placetype-to-csv -R . -l -p postalcode
wof-bundle-placetypes -R . -d /usr/local/data/whosonfirst-bundles/ -p postalcode -S latest --aws-bucket whosonfirst.mapzen.com --wof-clone /usr/local/bin/wof-clone-metafiles 
```

**Comment by thisisaaronland** [comment]
@vesameskanen - When you have a moment can you take a look at the files listed below and confirm that they are what you're after?

I am still working through the mechanics of how/where to automate bundles for non-admin (the default `whosonfirst-data` repo) placetypes but in the meantime:

http://whosonfirst.mapzen.com.s3.amazonaws.com/bundles/wof-postalcode-fi-latest-bundle.tar.bz2

http://whosonfirst.mapzen.com.s3.amazonaws.com/bundles/wof-postalcode-fi-latest-bundle.tar.bz2.sha1.txt

http://whosonfirst.mapzen.com.s3.amazonaws.com/bundles/wof-postalcode-fi-latest.csv

http://whosonfirst.mapzen.com.s3.amazonaws.com/bundles/wof-postalcode-fi-latest.csv.sha1.txt

**Comment by vesameskanen** [comment]
Hi @thisisaaronland - many thanks for the data links above. This seems to be the data we need. I tested Pelias WOF mapping with a new postalcode extension and the data above. 97 % of tested FI address entries with a known postalcode mapped correctly. The 3 % difference is probably caused by source data errors and maybe also by Pelias WOF mapping inaccuracy.

**Comment by thisisaaronland** [comment]
Perfect! These will be automated shortly although given (relatively) rarely postal codes change it may be a moot point :-)
