### ISSUE TITLE
Postalcode bundles are empty

### ISSUE THREAD

**Issue by dianashk** [whosonfirst/py-mapzen-whosonfirst-bundles#5]
An attempt to download the postalcode bundle yesterday (02/01/17) resulted in an empty shell. The metadata file contained the header rows, but nothing else. 😿

**Comment by thisisaaronland** [comment]
Not actually a bug. Any `postalcode-latest` files that were created were from June 2016 and probably part of experimental work. 

There is now a plain text index of all bundles at: https://whosonfirst.mapzen.com/bundles/index.txt
